### ISSUE TITLE
LUA error when opening Blizzards "Edit Mode"

### ISSUE THREAD

**Issue by Dmeister406** [ETSeki/prat-3-0#1]
1x [ADDON_ACTION_FORBIDDEN] AddOn 'Prat-3.0-@project-version@' tried to call the protected function 'ClearTarget()'.
[string "@Interface/AddOns/!BugGrabber/BugGrabber.lua"]:480: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `ClearTarget'
[string "@Interface/FrameXML/EditModeManager.lua"]:1496: in function `ResetTargetAndFocus'
[string "@Interface/FrameXML/EditModeManager.lua"]:1531: in function `RefreshTargetAndFocus'
[string "@Interface/FrameXML/EditModeManager.lua"]:1462: in function `OnEditModeEnter'
[string "@Interface/FrameXML/EditModeManager.lua"]:171: in function `EnterEditMode'
[string "@Interface/FrameXML/EditModeManager.lua"]:193: in function <Interface/FrameXML/EditModeManager.lua:191>
[string "=[C]"]: in function `Show'
[string "@Interface/FrameXML/UIParent.lua"]:2844: in function `SetUIPanel'
[string "@Interface/FrameXML/UIParent.lua"]:2648: in function `ShowUIPanel'
[string "@Interface/FrameXML/UIParent.lua"]:2552: in function <Interface/FrameXML/UIParent.lua:2548>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/FrameXML/UIParent.lua"]:3150: in function `ShowUIPanel'
[string "*GameMenuFrame.xml:94_OnClick"]:2: in function <[string "*GameMenuFrame.xml:94_OnClick"]:1>

**Comment by ETSeki** [comment]
This seems to be an issue with multiple addons and im not sure what is the cause because i already checked if prat tries to use cleartarget at any point and it doesnt. i will lock tomorrow if someone knows how to fix it.

**Comment by ETSeki** [comment]
All future Development will hapen under https://github.com/Legacy-of-Sylvanaar/prat-3-0 which is the branch that is connected to curseforge.
