### ISSUE TITLE
Double Timestamp

### ISSUE THREAD

**Issue by Hyphie24** [ETSeki/prat-3-0#3]
When someone emotes or an NPC has dialog you get double timestamp when the default wow timestamps are turned on

Before DF it would only have 1 timestamp regardless of emote or dialog

I tried digging through the Timestamps file for what could've been changed from SL to DF, but haven't figured out what could be the causing it and hopefully having another pair of eyes looking at it could find it

It only does it with emotes or dialog, normal game functions (such as loot or text from players) have a single timestamp

Thank you for uploading this, I had edited my own files as well, but hadn't made my own github for it

![Prat Timestamp](https://user-images.githubusercontent.com/31455641/198497471-80b1a42d-227a-4218-b33e-e75974a1c7d7.png)

**Comment by ETSeki** [comment]
I tried to reproduce this with the dialog of lorewalker cho at the beginning of siege of ogrimar but everything was fine. Could you check if this error occurrs if only prat is loaded and no other addons?

**Comment by Hyphie24** [comment]
No addons enabled, and getting it
![prat 1](https://user-images.githubusercontent.com/31455641/198760657-9094ff6e-e62d-4591-a22e-974f99027378.png)
![prat 2](https://user-images.githubusercontent.com/31455641/198760667-d1789030-b15a-415b-958d-7fff922afcb0.png)
![prat 3](https://user-images.githubusercontent.com/31455641/198760670-0f698647-9513-497a-b80f-59c5bcb53796.png)

It's not detrimental to me, it's not a serious issue, I was wondering if it is a new code line that has to be added into the timestamps file

**Comment by ETSeki** [comment]
Thank you i forgot that there is an ingame option for the timestamp. There arent any changes to the timestamp.lua so i guess something on blizzards side changed which prevents prat from blocking the timestamps so right now the best solution i can offer is to diable the timestamps in the blizzard ui.

**Comment by Hyphie24** [comment]
Yea, and with that don't see times for communities or guild chat from the community window. Like I said it's not huge, wanted to get another look on it. Thanks again 😁

**Comment by ETSeki** [comment]
All future Development will hapen under https://github.com/Legacy-of-Sylvanaar/prat-3-0 which is the branch that is connected to curseforge.
