### ISSUE TITLE
Linking Items is Bugged

### ISSUE THREAD

**Issue by Zorcan2112** [ETSeki/prat-3-0#4]
**Describe the bug**
When I link mounts into any chat, what appears on my side is a string of characters, and not a clickable link.  Based on what others who see the link say, the mount is appearing ok for them, with a clickable link, but it is not appearing as a link on my end.  Only seems to be with mounts.  

I can link pets, or items from my bag, or achievements with no issues, links are appearing.  However, all links while appearing correctly, also display my character level beside the link.  Both issues only started occurring with Dragonflight.

I am currently using DF1.4

**To Reproduce**
Link a mount in any chat (guild, whispers, party chat), it will appear as a garbled string of characters.
Links of any other type (items from bags, achievements, pets) work, but add character level before the link.

**Expected behavior**
For the link to appear as normal,

**Screenshots**
![What I see with links](https://user-images.githubusercontent.com/116864043/198509826-5dd3ebd7-f80b-4430-b9ea-56e4ec96276d.jpg)
The 1st whisper is an example of what I see for mounts.  The 2nd whisper is what I mean by character level appearing in the item link.

**Version Information (please complete the following information):**
 - Wow Version: current Retail
 - Prat Version: DF1.4

**Comment by Hyphie24** [comment]
Do you have any other chat addons running? I do not encounter this error on DF 1.4

**Comment by Zorcan2112** [comment]
You're correct.  Looks like it was a conflict with another addon.  Issue resolved.
