### ISSUE TITLE
Add a tagged release for WowUp support

### ISSUE THREAD

**Issue by derickso** [ETSeki/prat-3-0#6]
Add applicable zip file so Github repo can be tagged for updates

> GitHub Note
> 
> Not all GitHub repositories will work with the import process. In order for WowUp to be able to install an addon from GitHub the author must have created a tagged release. That tagged release must then contain a packaged zip file that WowUp can find.
> 
> A good example of a working GitHub repo is the official [WowUp Addon Example](https://github.com/WowUp/WowUp.Addon).

**Comment by ETSeki** [comment]
It looks like the Legacy of Sylvanar fork is active and pushing updates to curseforge again so i will commit my changes there so they get released in the official updates and are automaticly pushed to everyone who downloaded the addon.
