### ISSUE TITLE
Bug - can't resize chat frame

### ISSUE THREAD

**Issue by vautrin88** [ETSeki/prat-3-0#9]
Hello! 
Thank you so much for updating Prat for 10.0! 

Before 10.0 I used Prat to make chat box smaller, and now it doesn't work. 
Prat > Display Settings > Frame > Set Maximum Height 

No lua error, just doesn't seem to fix work.

Please take a look at the screenshots:
https://i.imgur.com/8FCKfLG.png

**Comment by ETSeki** [comment]
Hi this options shouldnt directly change the size of the window directly but change the restrictions for the normal ways to change the size. At the moment you can only change the main chat window in Blizzards edit mode so if you set the minimum height low enough you shoul be able to make the chat as small as in Shadowlands.
